[app]
# profile = "km"   # run only this named profile
# query_only = true         # test queries without syncing to writers

[ollama]
host = "http://machine3.local:11434"
model = "gemma4"

[[searches]]
name               = "gis"
query              = "gis"
days_back          = 90
discord_channel_id = "1506436270887534622"
# sharepoint_list_id = ""

[[searches]]
name               = "km"
query              = "\"knowledge management\""
q_mode             = "EXACT"
days_back          = 90
discord_channel_id = "1506665829465587833"
# sharepoint_list_id = ""
